# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929358b7ec2834ddeb1e0d6e3c1159ecace22e042495e3dc86fab63409f512f9317a0ca89b53f28c02e1ecad9520896b0f93164440417d2f521e0040ef631f55

test:
  secret_key_base: 0748509899f471b9b513345ee0adc57d15df930906ab442d90a6ccf9824d09b593cafa1cade7003e44e0b733e621348052f31f0bbb34aede9c838339ec023062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
